"""add_schedule_preferences

Revision ID: 6cdac5af4e08
Revises: a05f29076912
Create Date: 2026-04-06 12:04:54.917605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cdac5af4e08'
down_revision: Union[str, Sequence[str], None] = 'a05f29076912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('preferred_day', sa.Text(), server_default='monday', nullable=False))
    op.add_column('subscribers', sa.Column('preferred_hour', sa.Integer(), server_default='9', nullable=False))
    op.add_column('subscribers', sa.Column('timezone', sa.Text(), server_default='America/New_York', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'timezone')
    op.drop_column('subscribers', 'preferred_hour')
    op.drop_column('subscribers', 'preferred_day')
    # ### end Alembic commands ###
