"""drop article_analyses table

Revision ID: a05f29076912
Revises: 9296d4bbe254
Create Date: 2026-04-04 23:10:09.753422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a05f29076912'
down_revision: Union[str, Sequence[str], None] = '9296d4bbe254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_analyses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_analyses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('relevance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pe_insight', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_competitor_alert', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('included_in_digest_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('article_analyses_article_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('article_analyses_company_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['included_in_digest_id'], ['digests.id'], name=op.f('article_analyses_included_in_digest_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('article_analyses_pkey')),
    sa.UniqueConstraint('article_id', 'company_id', name=op.f('article_analyses_article_id_company_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
